staging_fb_ads:
    constraints:
        not_null:
            - unique_id
        unique:
            - unique_id

staging_fb_ad_insights:
    constraints:
        unique:
            - id

staging_fb_adsets:
    constraints:
        not_null:
            - id
        unique:
            - id
